<a href="https://colab.research.google.com/github/yjjo94/class2021spring/blob/main/20210426.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
%matplotlib inline
from matplotlib import pyplot as plt
import IPython.display as ipd
import numpy as np
from scipy.signal import lfilter

In [14]:
# parameter setting
amp = 1          # range [0.0, 1.0]
sr = 10000       # sampling rate, Hz
dur = 0.5        # in seconds
freq = 100.0     # sine frequency, Hz

In [15]:
# generate time
t = np.arange(1, sr * dur+1)/sr

In [17]:
# generate phase
theta = t * 2*np.pi * freq   

In [18]:
# generate signal by cosine-phasor
s = np.sin(theta)

In [20]:
def phasor(amp, sr, dur, freq):
     return s, theta, t
IDK = phasor(1, 10000, 0.5, 100.0)
IDK

(array([ 6.27905195e-02,  1.25333234e-01,  1.87381315e-01, ...,
        -1.25333234e-01, -6.27905195e-02,  1.96438672e-15]),
 array([6.28318531e-02, 1.25663706e-01, 1.88495559e-01, ...,
        3.14033602e+02, 3.14096434e+02, 3.14159265e+02]),
 array([1.000e-04, 2.000e-04, 3.000e-04, ..., 4.998e-01, 4.999e-01,
        5.000e-01]))